FROM openresty/openresty:1.27.1.2-0-alpine-fat

RUN opm get ledgetech/lua-resty-http \
    && opm get fffonion/lua-resty-openssl

RUN mkdir -p /var/log/sparrow/gateway

COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY lua /usr/local/openresty/nginx/lua

EXPOSE 8088 1883

CMD ["openresty", "-g", "daemon off;"]
